### ISSUE TITLE
Implement Crowdsource video experiments cross platform desktop application

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-crowdsource-dnn-optimization#1]
Proposal available for main contributors  here 
https://docs.google.com/document/d/1Sz6gqahcaOQiQi-3R4miF195N-ORAHumIc_D9RpROz8/edit#heading=h.fjhsrumqmltx

**Comment by DVEfremov** [comment]
Items should be implemented first of all:
* Resolve repo URL 
* Init and cache platform features 
* Fetch scenarios 
* Download scenario files 
* Run executable for selected scenario 
* Parse recognition (execution) result and display under appropriate image frame

**Comment by DVEfremov** [comment]
I've asked our designer to create mock-ups (coud be the same theme as for android if you don't mind) 
(https://github.com/xored/design/issues/101 link available only for xored team but it will help me check the issue state)

**Comment by dsavenko** [comment]
This is done, closing.
