### ISSUE TITLE
Automate app packaging

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-crowdsource-dnn-optimization#11]
@Chunosov 
Please describe steps of manual packaging from original sources 
Then we will try to automate and add to CI (travis)

**Comment by Chunosov** [comment]
Added redist script in #10

**Comment by dsavenko** [comment]
Redists scripts are there. Making the app buildable properly via CK is a big story which will be covered by other, more specific tasks (the first one of them is #25). So, closing this ticket.
