### ISSUE TITLE
refresh selection items on "select" if ck env was changed

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-crowdsource-dnn-optimization#16]
If app has been run allready it keeps same list of engines, models and imagenet set 
if some packages were installed   after app has been started 
seletion items keep the same but it will be usefull not to force app restart after all changes in ck env.

**Comment by dsavenko** [comment]
I'd say this is a low priority (let's add a special label for such tasks).

**Comment by dsavenko** [comment]
This task doesn't fit well into the new operational model (i.e. engines/models/imagenets/etc are now filled via the preprocess script before the app runs). It was a low priority anyway, as for the demo app it's not that necessary. So, closing this ticket as it's unlikely to be done in the near future. Feel free to reopen, if you think this feature is important.
