### ISSUE TITLE
Segmentation fault sometimes

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-crowdsource-dnn-optimization#17]
On my notebook 
Core i5, 8 RAM 
after 3-4 images for CPU engine  I've got Segmentation fault 
Valgrind log for details:
[segmentation_fault_2017_02_08.txt](https://github.com/dividiti/crowdsource-video-experiments-on-desktop/files/762761/segmentation_fault_2017_02_08.txt)

**Comment by dsavenko** [comment]
Fixed in PR https://github.com/dividiti/crowdsource-video-experiments-on-desktop/pull/24
