### ISSUE TITLE
TODO: Show caffe lib names in the engine selector, not proxy names

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-crowdsource-dnn-optimization#20]
@psyhtest : user would expect to see not the available dnn-proxy libs in the Caffe engine menu, but the actual installed Caffe libs that are returned by `ck show env --tags=lib,caffe`

**Comment by psyhtest** [comment]
... and, in the future, TensorFlow, TensorRT, etc

**Comment by dsavenko** [comment]
Done in PR https://github.com/dividiti/crowdsource-video-experiments-on-desktop/pull/24
