### ISSUE TITLE
Use images/second as the performance metric

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-crowdsource-dnn-optimization#21]
I'm finding "Images per second" (fps) more intuitive as a performance metric than "Time per image" (especially when the unit of measurement has to be guessed:)). 

I think we should just display "Images per second" (or "Image/s" if space is limited).

**Comment by dsavenko** [comment]
Done. It now looks like this:

![screenshot from 2017-02-20 20-14-16](https://cloud.githubusercontent.com/assets/555363/23126447/386a5a4c-f7a9-11e6-869c-9105f6ebebe4.png)

Closing the issue. Please feel free to reopen if it's not what you meant.
