### ISSUE TITLE
CK path is not correctly detected on Surface Pro 4

### ISSUE THREAD

**Issue by gfursin** [dividiti/ck-crowdsource-dnn-optimization#30]
I tried this app on a new Surface Pro 4 installing CK via pip using Anaconda3 python ... I get the following error: 

Classification program stopped prematurely. Please, select the command below, copy it and run manually from command line to investigate the issue:

python -W ignore::DeprecationWarning C:\Users\ckdnn\Anaconda3\Scripts\..\ck\kernel.py run program:caffe-classification-opencl --cmd_key=use_continuous --deps.caffemodel=8a0758effe14ae49 --deps.imagenet-aux=eb8b1076f899bf92 --deps.imagenet-val=2e35bb4b714d49aa

When I run it, I gets the following:

C:\Users\ckdnn\Anaconda3\python.EXE: can't open file 'C:\Users\ckdnn\Anaconda3\Scripts\..\ck\kernel.py': [Errno 2] No such file or directory

However, I can run this fine:

run program:caffe-classification-opencl --cmd_key=use_continuous --deps.caffemodel=8a0758effe14ae49 --deps.imagenet-aux=eb8b1076f899bf92 --deps.imagenet-val=2e35bb4b714d49aa

The problem is that Anaconda uses slightly different mechanism for packages so you can't find kernel there ... As I mentioned, it may be better to run ck directly rather than trying to find kernel since I spent some time figuring out how to make it portable (it's not straightforward), what do you think, @dsavenko ?

Thanks a lot!!!

**Comment by dsavenko** [comment]
The old desktop demo runs `python` on Windows, and `ck` directly on Linux. I didn't change this behaviour, however its reasons are unclear for me. Probably, we can just get rid of this separation and run `ck` directly on Windows as well. I will investigate this.

**Comment by gfursin** [comment]
Ah, ok. Yes, I would prefer just to run ck on both Windows and Linux ... Thanks!

**Comment by dsavenko** [comment]
Should be fixed
