### ISSUE TITLE
file squeezenet_v1.1.caffemodel has invalid MD5 stored in scenarios

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-crowdsource-dnn-optimization#4]
Check MD5: failed for "/home/nikolay/Projects/crowdsource-video-experiments-on-desktop/bin/openscience/data/87f5e203c47544d6/model/**squeezenet_v1.1.caffemodel**" calculated: "42c581aa4ef6d5978287df3bbb9137f1" stored: "0357e4e11d173c72a01615888826bc8e"
FAIL "Downloading file 'squeezenet_v1.1.caffemodel' from **https://github.com/DeepScale/SqueezeNet/blob/master/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel?raw=true** into /home/nikolay/Projects/crowdsource-video-experiments-on-desktop/bin/openscience/data/87f5e203c47544d6/model" "MD5 verification failed"

**Comment by psyhtest** [comment]
I've checked on a couple of machines: `0357e4e11d173c72a01615888826bc8e` is correct.

I am a bit suspicious about  the URL ending with `?raw=true` here, though. On some machines, this URL worked fine. On other machines, it resulted in a ~33K file - an obvious failure to download.

I believe the URL should be changed to `https://github.com/DeepScale/SqueezeNet/raw/master/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel` as in [ck-caffe/package/caffemodel-deepscale-squeezenet-1.1/.cm/meta.json](https://github.com/dividiti/ck-caffe/blob/master/package/caffemodel-deepscale-squeezenet-1.1/.cm/meta.json):
```
      "MODEL_URL": "https://github.com/DeepScale/SqueezeNet/raw/master/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel",
      "MODEL_FILE": "squeezenet_v1.1.caffemodel",
      "MODEL_HASH_CALCULATOR": "sha1sum",
      "MODEL_HASH_REF": "3397f026368a45ae236403ccc81cfcbe8ebe1bd0"
    },
```
Just not quite sure where the change should be made.

**Comment by Chunosov** [comment]
I looked into downloaded file, and it only contain text:

`<html><body>You are being <a href="https://github.com/DeepScale/SqueezeNet/raw/master/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel">redirected</a>.</body></html>`

Obviously, it is not correct file. But this url is in the scenario json-file:

```
                    {
                        "file_size": 4950080,
                        "filename": "squeezenet_v1.1.caffemodel",
                        "md5": "0357e4e11d173c72a01615888826bc8e",
                        "model_weights": "yes",
                        "path": "data/87f5e203c47544d6/model",
                        "url": "https://github.com/DeepScale/SqueezeNet/blob/master/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel?raw=true"
                    }
```
and scenario was downloaded from `http://cknowledge.org/repo/json.php? ` when platform features was:
```
{
    "cpu": {
        "cpu_abi": "armeabi-v7a",
        "cpu_features": "swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt",
        "max_freq": {
            "0": 1300,
            "1": 1300,
            "2": 1300,
            "3": 1300,
            "4": 1900,
            "5": 1900,
            "6": 1900,
            "7": 1900
        },
        "name": "Samsung EXYNOS5433",
        "num_proc": "8",
        "sub_name": ""
    },
    "cpu_uid": "16270e7f2844ab79",
    "cpu_uoa": "16270e7f2844ab79",
    "gpu": {
        "name": "ARM Mali-T760",
        "vendor": "ARM"
    },
    "gpu_misc": {
        "opencl_lib_present": "no"
    },
    "gpu_uid": "8ea3d7446e912b92",
    "gpu_uoa": "8ea3d7446e912b92",
    "os": {
        "bits": "32",
        "name": "Android 5.0.1",
        "name_long": "Linux version 3.10.9-4841555 (dpi@SWDD3004) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Wed May 6 15:15:31 KST 2015",
        "name_short": "Linux version 3.10.9"
    },
    "os_uid": "382cae4a2e82853d",
    "os_uoa": "382cae4a2e82853d",
    "platform": {
        "model": "SM-N910C",
        "name": "SAMSUNG SM-N910C",
        "vendor": "SAMSUNG"
    },
    "platform_uid": "1924152a7004ec09",
    "platform_uoa": "1924152a7004ec09"
}

```

**Comment by Chunosov** [comment]
One more observation: when I tried to get scenario file with empty platform features (`{}`) it was downloaded anyway, but scenarios were different than when platform features were filled.

**Comment by Chunosov** [comment]
Not actual due to changed app algorithm - no repositories are not used anymore
