### ISSUE TITLE
Probably bug when recognition with SqueezeNet

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-crowdsource-dnn-optimization#9]
```
Worst prediction found with marker value 0.001
Image: "/home/anton/data1/ILSVRC2012_val/ILSVRC2012_val_00015268.JPEG"
Top-1: "0.001 - tiger shark, Galeocerdo cuvieri (3)"
Correct: "0 - tobacco shop, tobacconist shop, tobacconist (860)"
```
It seems that SqueezeNet can't predict any image and think they all are tiger shark

**Comment by psyhtest** [comment]
Apologies for the false alarm! It must have been due to corrupted SqueezeNet installations on my machine. After reinstalling the SqueezeNet packages, the app works like a charm!
